package com.bala.cascade_error;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Class1206 implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Class1206() {
    }




}